/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ProgramlarRouteImport } from './routes/programlar'
import { Route as AtolyeWorkshopIdRouteImport } from './routes/atolye.$workshopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramlarRoute = ProgramlarRouteImport.update({
  id: '/programlar',
  path: '/programlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AtolyeWorkshopIdRoute = AtolyeWorkshopIdRouteImport.update({
  id: '/atolye/$workshopId',
  path: '/atolye/$workshopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/hakkimizda' | '/panel' | '/programlar' | '/atolye/$workshopId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hakkimizda' | '/panel' | '/programlar' | '/atolye/$workshopId'
  id:
    | '__root__'
    | '/'
    | '/hakkimizda'
    | '/panel'
    | '/programlar'
    | '/atolye/$workshopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  PanelRoute: typeof PanelRoute
  ProgramlarRoute: typeof ProgramlarRoute
  AtolyeWorkshopIdRoute: typeof AtolyeWorkshopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programlar': {
      id: '/programlar'
      path: '/programlar'
      fullPath: '/programlar'
      preLoaderRoute: typeof ProgramlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atolye/$workshopId': {
      id: '/atolye/$workshopId'
      path: '/atolye/$workshopId'
      fullPath: '/atolye/$workshopId'
      preLoaderRoute: typeof AtolyeWorkshopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  PanelRoute: PanelRoute,
  ProgramlarRoute: ProgramlarRoute,
  AtolyeWorkshopIdRoute: AtolyeWorkshopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
