/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HaftalikProgramRouteImport } from './routes/haftalik-program'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as MinvalSanatRouteImport } from './routes/minval-sanat'
import { Route as OgrenciRouteImport } from './routes/ogrenci'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ProgramlarRouteImport } from './routes/programlar'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAyarlarRouteImport } from './routes/admin.ayarlar'
import { Route as AdminBasvurularRouteImport } from './routes/admin.basvurular'
import { Route as AdminOdevlerRouteImport } from './routes/admin.odevler'
import { Route as AdminOgrencilerRouteImport } from './routes/admin.ogrenciler'
import { Route as AdminSiniflarRouteImport } from './routes/admin.siniflar'
import { Route as AdminYoklamaRouteImport } from './routes/admin.yoklama'
import { Route as AtolyeWorkshopIdRouteImport } from './routes/atolye.$workshopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HaftalikProgramRoute = HaftalikProgramRouteImport.update({
  id: '/haftalik-program',
  path: '/haftalik-program',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const MinvalSanatRoute = MinvalSanatRouteImport.update({
  id: '/minval-sanat',
  path: '/minval-sanat',
  getParentRoute: () => rootRouteImport,
} as any)
const OgrenciRoute = OgrenciRouteImport.update({
  id: '/ogrenci',
  path: '/ogrenci',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramlarRoute = ProgramlarRouteImport.update({
  id: '/programlar',
  path: '/programlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAyarlarRoute = AdminAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBasvurularRoute = AdminBasvurularRouteImport.update({
  id: '/basvurular',
  path: '/basvurular',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOdevlerRoute = AdminOdevlerRouteImport.update({
  id: '/odevler',
  path: '/odevler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOgrencilerRoute = AdminOgrencilerRouteImport.update({
  id: '/ogrenciler',
  path: '/ogrenciler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiniflarRoute = AdminSiniflarRouteImport.update({
  id: '/siniflar',
  path: '/siniflar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYoklamaRoute = AdminYoklamaRouteImport.update({
  id: '/yoklama',
  path: '/yoklama',
  getParentRoute: () => AdminRoute,
} as any)
const AtolyeWorkshopIdRoute = AtolyeWorkshopIdRouteImport.update({
  id: '/atolye/$workshopId',
  path: '/atolye/$workshopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/haftalik-program': typeof HaftalikProgramRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/minval-sanat': typeof MinvalSanatRoute
  '/ogrenci': typeof OgrenciRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/basvurular': typeof AdminBasvurularRoute
  '/admin/odevler': typeof AdminOdevlerRoute
  '/admin/ogrenciler': typeof AdminOgrencilerRoute
  '/admin/siniflar': typeof AdminSiniflarRoute
  '/admin/yoklama': typeof AdminYoklamaRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/haftalik-program': typeof HaftalikProgramRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/minval-sanat': typeof MinvalSanatRoute
  '/ogrenci': typeof OgrenciRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/basvurular': typeof AdminBasvurularRoute
  '/admin/odevler': typeof AdminOdevlerRoute
  '/admin/ogrenciler': typeof AdminOgrencilerRoute
  '/admin/siniflar': typeof AdminSiniflarRoute
  '/admin/yoklama': typeof AdminYoklamaRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/haftalik-program': typeof HaftalikProgramRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/minval-sanat': typeof MinvalSanatRoute
  '/ogrenci': typeof OgrenciRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/basvurular': typeof AdminBasvurularRoute
  '/admin/odevler': typeof AdminOdevlerRoute
  '/admin/ogrenciler': typeof AdminOgrencilerRoute
  '/admin/siniflar': typeof AdminSiniflarRoute
  '/admin/yoklama': typeof AdminYoklamaRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/haftalik-program'
    | '/hakkimizda'
    | '/iletisim'
    | '/minval-sanat'
    | '/ogrenci'
    | '/panel'
    | '/programlar'
    | '/admin/ayarlar'
    | '/admin/basvurular'
    | '/admin/odevler'
    | '/admin/ogrenciler'
    | '/admin/siniflar'
    | '/admin/yoklama'
    | '/atolye/$workshopId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/haftalik-program'
    | '/hakkimizda'
    | '/iletisim'
    | '/minval-sanat'
    | '/ogrenci'
    | '/panel'
    | '/programlar'
    | '/admin/ayarlar'
    | '/admin/basvurular'
    | '/admin/odevler'
    | '/admin/ogrenciler'
    | '/admin/siniflar'
    | '/admin/yoklama'
    | '/atolye/$workshopId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/haftalik-program'
    | '/hakkimizda'
    | '/iletisim'
    | '/minval-sanat'
    | '/ogrenci'
    | '/panel'
    | '/programlar'
    | '/admin/ayarlar'
    | '/admin/basvurular'
    | '/admin/odevler'
    | '/admin/ogrenciler'
    | '/admin/siniflar'
    | '/admin/yoklama'
    | '/atolye/$workshopId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HaftalikProgramRoute: typeof HaftalikProgramRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  MinvalSanatRoute: typeof MinvalSanatRoute
  OgrenciRoute: typeof OgrenciRoute
  PanelRoute: typeof PanelRoute
  ProgramlarRoute: typeof ProgramlarRoute
  AtolyeWorkshopIdRoute: typeof AtolyeWorkshopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haftalik-program': {
      id: '/haftalik-program'
      path: '/haftalik-program'
      fullPath: '/haftalik-program'
      preLoaderRoute: typeof HaftalikProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minval-sanat': {
      id: '/minval-sanat'
      path: '/minval-sanat'
      fullPath: '/minval-sanat'
      preLoaderRoute: typeof MinvalSanatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogrenci': {
      id: '/ogrenci'
      path: '/ogrenci'
      fullPath: '/ogrenci'
      preLoaderRoute: typeof OgrenciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programlar': {
      id: '/programlar'
      path: '/programlar'
      fullPath: '/programlar'
      preLoaderRoute: typeof ProgramlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ayarlar': {
      id: '/admin/ayarlar'
      path: '/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AdminAyarlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/basvurular': {
      id: '/admin/basvurular'
      path: '/basvurular'
      fullPath: '/admin/basvurular'
      preLoaderRoute: typeof AdminBasvurularRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/odevler': {
      id: '/admin/odevler'
      path: '/odevler'
      fullPath: '/admin/odevler'
      preLoaderRoute: typeof AdminOdevlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ogrenciler': {
      id: '/admin/ogrenciler'
      path: '/ogrenciler'
      fullPath: '/admin/ogrenciler'
      preLoaderRoute: typeof AdminOgrencilerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/siniflar': {
      id: '/admin/siniflar'
      path: '/siniflar'
      fullPath: '/admin/siniflar'
      preLoaderRoute: typeof AdminSiniflarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/yoklama': {
      id: '/admin/yoklama'
      path: '/yoklama'
      fullPath: '/admin/yoklama'
      preLoaderRoute: typeof AdminYoklamaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/atolye/$workshopId': {
      id: '/atolye/$workshopId'
      path: '/atolye/$workshopId'
      fullPath: '/atolye/$workshopId'
      preLoaderRoute: typeof AtolyeWorkshopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAyarlarRoute: typeof AdminAyarlarRoute
  AdminBasvurularRoute: typeof AdminBasvurularRoute
  AdminOdevlerRoute: typeof AdminOdevlerRoute
  AdminOgrencilerRoute: typeof AdminOgrencilerRoute
  AdminSiniflarRoute: typeof AdminSiniflarRoute
  AdminYoklamaRoute: typeof AdminYoklamaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAyarlarRoute: AdminAyarlarRoute,
  AdminBasvurularRoute: AdminBasvurularRoute,
  AdminOdevlerRoute: AdminOdevlerRoute,
  AdminOgrencilerRoute: AdminOgrencilerRoute,
  AdminSiniflarRoute: AdminSiniflarRoute,
  AdminYoklamaRoute: AdminYoklamaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HaftalikProgramRoute: HaftalikProgramRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  MinvalSanatRoute: MinvalSanatRoute,
  OgrenciRoute: OgrenciRoute,
  PanelRoute: PanelRoute,
  ProgramlarRoute: ProgramlarRoute,
  AtolyeWorkshopIdRoute: AtolyeWorkshopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
