/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as MinvalSanatRouteImport } from './routes/minval-sanat'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ProgramlarRouteImport } from './routes/programlar'
import { Route as AtolyeWorkshopIdRouteImport } from './routes/atolye.$workshopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const MinvalSanatRoute = MinvalSanatRouteImport.update({
  id: '/minval-sanat',
  path: '/minval-sanat',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramlarRoute = ProgramlarRouteImport.update({
  id: '/programlar',
  path: '/programlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AtolyeWorkshopIdRoute = AtolyeWorkshopIdRouteImport.update({
  id: '/atolye/$workshopId',
  path: '/atolye/$workshopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/minval-sanat': typeof MinvalSanatRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/minval-sanat': typeof MinvalSanatRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/minval-sanat': typeof MinvalSanatRoute
  '/panel': typeof PanelRoute
  '/programlar': typeof ProgramlarRoute
  '/atolye/$workshopId': typeof AtolyeWorkshopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hakkimizda'
    | '/iletisim'
    | '/minval-sanat'
    | '/panel'
    | '/programlar'
    | '/atolye/$workshopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/hakkimizda'
    | '/iletisim'
    | '/minval-sanat'
    | '/panel'
    | '/programlar'
    | '/atolye/$workshopId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hakkimizda'
    | '/iletisim'
    | '/minval-sanat'
    | '/panel'
    | '/programlar'
    | '/atolye/$workshopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  MinvalSanatRoute: typeof MinvalSanatRoute
  PanelRoute: typeof PanelRoute
  ProgramlarRoute: typeof ProgramlarRoute
  AtolyeWorkshopIdRoute: typeof AtolyeWorkshopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minval-sanat': {
      id: '/minval-sanat'
      path: '/minval-sanat'
      fullPath: '/minval-sanat'
      preLoaderRoute: typeof MinvalSanatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programlar': {
      id: '/programlar'
      path: '/programlar'
      fullPath: '/programlar'
      preLoaderRoute: typeof ProgramlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atolye/$workshopId': {
      id: '/atolye/$workshopId'
      path: '/atolye/$workshopId'
      fullPath: '/atolye/$workshopId'
      preLoaderRoute: typeof AtolyeWorkshopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  MinvalSanatRoute: MinvalSanatRoute,
  PanelRoute: PanelRoute,
  ProgramlarRoute: ProgramlarRoute,
  AtolyeWorkshopIdRoute: AtolyeWorkshopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
