ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS hero_primary_label text NOT NULL DEFAULT 'Programlarımızı Keşfedin',
  ADD COLUMN IF NOT EXISTS hero_secondary_label text NOT NULL DEFAULT 'Ön Kayıt Ol',
  ADD COLUMN IF NOT EXISTS about_eyebrow text NOT NULL DEFAULT 'Hakkımızda',
  ADD COLUMN IF NOT EXISTS about_heading text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS about_link_label text NOT NULL DEFAULT 'Daha fazlası',
  ADD COLUMN IF NOT EXISTS about_section_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS programs_eyebrow text NOT NULL DEFAULT 'Programlarımız',
  ADD COLUMN IF NOT EXISTS programs_description text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS programs_button_label text NOT NULL DEFAULT 'Tüm Programlar',
  ADD COLUMN IF NOT EXISTS schedule_eyebrow text NOT NULL DEFAULT 'Haftalık Program',
  ADD COLUMN IF NOT EXISTS schedule_description text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cta_button_label text NOT NULL DEFAULT 'Ön Kayıt Formu',
  ADD COLUMN IF NOT EXISTS cta_section_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS stats_heading text NOT NULL DEFAULT 'Sayılarla Minval',
  ADD COLUMN IF NOT EXISTS stats_section_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS testimonials_heading text NOT NULL DEFAULT 'Katılımcılarımız ne diyor?',
  ADD COLUMN IF NOT EXISTS testimonials_section_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS faq_heading text NOT NULL DEFAULT 'Sıkça Sorulan Sorular',
  ADD COLUMN IF NOT EXISTS faq_section_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS principles_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS stats_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS testimonials_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS faq_json jsonb NOT NULL DEFAULT '[]'::jsonb;